exclude: ^.github/actions/assigner/dist
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: ^docs
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: ^docs
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.1.0.2
    hooks:
    -   id: buildifier
        args:
          - --warnings=all
    -   id: buildifier-lint
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.13
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    -   id: mypy
        exclude: "^py/torch_tensorrt/fx|^examples|^tests|^py/torch_tensorrt/dynamo/_experimental|^tools|^docs|noxfile.py|setup.py|versions.py"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        exclude: ^examples/custom_converters/elu_converter/setup.py|^docs
  - repo: local
    hooks:
    -   id: dont-commit-upstream
        name: NVIDIA-INTERNAL check
        entry: "!NVIDIA-INTERNAL"
        exclude: "^.pre-commit-config.yaml"
        language: pygrep
        types: [text]
